// Generated by https://quicktype.io
using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace TerminDoc.Models
{
    

    public class Holiday
    {
        
        [JsonProperty("holidays")]
        public List<holidayModel> Holidays { get; set; }
    }

    public class holidayModel
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("date")]
        //[DisplayFormat(DateFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [JsonProperty("observed")]  
        //[DisplayFormat(DateFormString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Observed { get; set; }

        [JsonProperty("public")]
        public bool Public { get; set; }

        [JsonProperty("weekday")]
        public Weekday Weekday { get; set; }

    }
    public class Weekday
    {
        [JsonProperty("date")]
        public Date Date { get; set; }

        [JsonProperty("observed")]
        public Date Observed { get; set; }
    }

    public class Date
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("numeric")]
        public long Numeric { get; set; }
    }

  


}
